FROM n8nio/n8n:1.114.0

USER root
RUN npm install -g @aws-sdk/client-s3

USER node

ENV GENERIC_TIMEZONE="Europe/Paris"
ENV TZ="Europe/Paris"
ENV DB_SQLITE_POOL_SIZE=1
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_BLOCK_ENV_ACCESS_IN_NODE=false
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV N8N_DEFAULT_BINARY_DATA_MODE=filesystem
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV NODE_FUNCTION_ALLOW_BUILTIN="*"
ENV NODE_FUNCTION_ALLOW_EXTERNAL="@aws-sdk/client-s3"
