FROM node:24-alpine

USER root
RUN npm i -g n8n@1.114.4
RUN npm i -g @aws-sdk/client-s3

ENV NODE_FUNCTION_ALLOW_EXTERNAL="@aws-sdk/client-s3"
ENV NODE_FUNCTION_ALLOW_BUILTIN="*"

ENV GENERIC_TIMEZONE="Europe/Paris"
ENV TZ="Europe/Paris"
ENV DB_SQLITE_POOL_SIZE=1
ENV N8N_RUNNERS_ENABLED=true
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV N8N_DEFAULT_BINARY_DATA_MODE=filesystem
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

USER node

ENTRYPOINT ["n8n"]
